### PR TITLE
Bump versions

### PR DESCRIPTION
**Pull request by sebigavril**
Bump versions:
 - dependencies & plugins
 - sbt
 - scala (2.12.2)

### CODE REVIEW

**Review by raboof — APPROVED** [review]
Nice thanks!

IMHO we can merge this as-is without introducing cross-compilation: cakemix is rather stable, so users who are still at older versions can just keep using an older version of cakemix, too. Agreed?

**Comment by sebigavril** [comment]
Agree - i don't see any open code issues or PRs

**Comment by gvandeglind** [comment]
Agreed, LGTM

**Comment by gvandeglind** [comment]
@raboof how to release cakemix?

**Comment by raboof** [comment]
https://github.com/xebia/cakemix/blob/master/CONTRIBUTING.md#releasing ? :)

**Comment by gvandeglind** [comment]
thanks, will give it a try

**Pull request merged**
